//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emiliAppraisal.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class emiliEntities : DbContext
    {
        public emiliEntities()
            : base("name=emiliEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int GetNextCMHCNo(Nullable<int> nextCMHCNO, Nullable<int> ii)
        {
            var nextCMHCNOParameter = nextCMHCNO.HasValue ?
                new ObjectParameter("NextCMHCNO", nextCMHCNO) :
                new ObjectParameter("NextCMHCNO", typeof(int));

            var iiParameter = ii.HasValue ?
                new ObjectParameter("ii", ii) :
                new ObjectParameter("ii", typeof(int));

            ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetNextCMHCNo", nextCMHCNOParameter, iiParameter);

            return (int)nextCMHCNOParameter.Value;
        }
    }
}
